### ISSUE TITLE
list not update automatly after add or pay

### ISSUE THREAD

**Issue by Paul75** [dt6120/Marketplace-Dapp#2]
Hello,

The list not automatically reload after add product or buy product.

Thanks

**Comment by dt6120** [comment]
It can be resolved by adding `window.location.reload()` after tx receipt is received in the `createProduct` and `purchaseProduct` functions (after lines 55 & 66 respectively) in the MainComponent.js file.

**Comment by Paul75** [comment]
thanks I test when i can.
now have problem before works now some wrong .... it not found any account ....

**Comment by Paul75** [comment]
I think I prefere do this : 

```
.once('receipt', async (receipt) => {
                // this.setState({ loading: false });
                // window.location.reload();
                this.setState({ products: [] });
                await this.loadBlockchainData();
            });
```

Not good ?

Thanks

**Comment by dt6120** [comment]
Yes, if it is working, then why not.
